#!/bin/bash
echo "Testing tiny_01";
./p1 -ast tests/tiny_01 > out.tree && diff tests/tiny_01.tree out.tree;
echo "Testing tiny_02";
./p1 -ast tests/tiny_02 > out.tree && diff tests/tiny_02.tree out.tree;
echo "Testing tiny_03";
./p1 -ast tests/tiny_03 > out.tree && diff tests/tiny_03.tree out.tree;
echo "Testing tiny_04";
./p1 -ast tests/tiny_04 > out.tree && diff tests/tiny_04.tree out.tree;
echo "Testing tiny_05";
./p1 -ast tests/tiny_05 > out.tree && diff tests/tiny_05.tree out.tree;
echo "Testing tiny_06";
./p1 -ast tests/tiny_06 > out.tree && diff tests/tiny_06.tree out.tree;
echo "Testing tiny_07";
./p1 -ast tests/tiny_07 > out.tree && diff tests/tiny_07.tree out.tree;
echo "Testing tiny_08";
./p1 -ast tests/tiny_08 > out.tree && diff tests/tiny_08.tree out.tree;
echo "Testing tiny_09";
./p1 -ast tests/tiny_09 > out.tree && diff tests/tiny_09.tree out.tree;
echo "Testing tiny_10";
./p1 -ast tests/tiny_10 > out.tree && diff tests/tiny_10.tree out.tree;
echo "Testing tiny_11";
./p1 -ast tests/tiny_11 > out.tree && diff tests/tiny_11.tree out.tree;
echo "Testing tiny_12";
./p1 -ast tests/tiny_12 > out.tree && diff tests/tiny_12.tree out.tree;
echo "Testing tiny_13";
./p1 -ast tests/tiny_13 > out.tree && diff tests/tiny_13.tree out.tree;
echo "Testing tiny_14";
./p1 -ast tests/tiny_14 > out.tree && diff tests/tiny_14.tree out.tree;
echo "Testing tiny_15";
./p1 -ast tests/tiny_15 > out.tree && diff tests/tiny_15.tree out.tree;
echo "Testing tiny_16";
./p1 -ast tests/tiny_16 > out.tree && diff tests/tiny_16.tree out.tree;
echo "Testing tiny_17";
./p1 -ast tests/tiny_17 > out.tree && diff tests/tiny_17.tree out.tree;
echo "Testing tiny_18";
./p1 -ast tests/tiny_18 > out.tree && diff tests/tiny_18.tree out.tree;
echo "Testing tiny_19";
./p1 -ast tests/tiny_19 > out.tree && diff tests/tiny_19.tree out.tree;
echo "Testing tiny_20";
./p1 -ast tests/tiny_20 > out.tree && diff tests/tiny_20.tree out.tree;
echo "Testing tiny_21";
./p1 -ast tests/tiny_21 > out.tree && diff tests/tiny_21.tree out.tree;
echo "Testing tiny_22";
./p1 -ast tests/tiny_22 > out.tree && diff tests/tiny_22.tree out.tree;
echo "Testing tiny_23";
./p1 -ast tests/tiny_23 > out.tree && diff tests/tiny_23.tree out.tree;
echo "Testing tiny_24";
./p1 -ast tests/tiny_24 > out.tree && diff tests/tiny_24.tree out.tree;
echo "Testing tiny_25";
./p1 -ast tests/tiny_25 > out.tree && diff tests/tiny_25.tree out.tree;
